# Generated by Django 4.1 on 2022-09-25 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128)),
                ('settings', models.TextField(null=True)),
                ('busy', models.BooleanField(default=False)),
                ('last_access', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('safety', models.BooleanField(default=True)),
                ('width', models.IntegerField(default=512)),
                ('height', models.IntegerField(default=512)),
                ('steps', models.IntegerField(default=25)),
                ('scale', models.FloatField(default=7.0)),
                ('seed', models.IntegerField(default=42)),
                ('init_strength', models.FloatField(null=True)),
                ('status', models.IntegerField(default=0)),
                ('added_date', models.DateTimeField()),
                ('init_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='init_image', to='mdrouter.file')),
                ('init_mask', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='init_mask', to='mdrouter.file')),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mdrouter.node')),
                ('output', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='output', to='mdrouter.file')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdrouter.user')),
            ],
        ),
    ]
