# Generated by Django 4.1 on 2022-09-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdrouter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
