# Generated by Django 4.1 on 2022-09-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdrouter', '0002_prompt_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='mode',
            field=models.CharField(default='txt2img', max_length=128),
        ),
    ]
