# Generated by Django 4.1 on 2022-09-27 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdrouter', '0003_prompt_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='mode',
            field=models.CharField(default='Text -> Image', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
